app/urls.py
from django.contrib import admin
from django.urls import path, include
import os

urlpatterns = [
    path('', include(('accounts.urls', 'accounts'))),
    path('asesoria/', include(('asesoria.urls', 'asesoria'))),
    path('admin/', admin.site.urls),
]

apps/accounts/urls.py
from django.urls import path, reverse_lazy
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_vies
from .views import ListarMaterias
from . import views


app_name = 'accounts'
urlpatterns = [
    path('', views.principal, name='principal'),
    path('registro/', views.registro, name='registro'),
    path('ingreso/', views.ingreso, name='ingreso'),
    path('salir/', views.salir, name='salir'),
    path('configurar/', views.configurar, name='configurar'),
    path('configurar/contrasena/', views.contrasena, name='contrasena'),
    path('configurar/horario/', views.horario, name='horario'),
    path('configurar/horario/eliminar/<str:pk>/', views.eliminarHorario, name='eliminar_horario'),
    path('contrasena_restablecer/',
         auth_vies.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done'),
                                             extra_context={'hide_logout': True, 'hide_config': True}),
         name='reset_password'),
    path('contrasena_restablecer_enviar/', auth_vies.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('contrasena_restablecer/<uidb64>/<token>/', auth_vies.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('contrasena_restablecer_terminado/',
         auth_vies.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('materia/', ListarMaterias.as_view(), name='listar_materias'),
    path('temario/', views.temario, name='temario'),
    path('temario/materia/<str:pk>', views.temarioMateriaEditar, name='temario_materia_editar'),
    path('temario/agregar/', views.temarioAgregarModal, name='temario_agregar_modal'),
    path('temario/agregar/<str:pk>/', views.temarioAgregar, name='temario_agregar'),
    path('temario/eliminar/<str:pk>/', views.temarioEliminar, name='temario_eliminar'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/asesoria/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', verAsesorias, name='ver_asesorias'),
    path('materia/', seleccionMateria, name='seleccion_materia'),
    path('materia/<str:materia>/tema/', seleccionTema, name='seleccion_tema'),
    path('materia/<str:materia>/tema/<str:tema>/subtema/',
         seleccionSubtema, name='seleccion_subtema'),
    path('materia/<str:materia>/tema/<str:tema>/subtema/<str:subtema>/asesor/',
         seleccionAsesor, name='seleccion_asesor'),
    path('materia/<str:materia>/tema/<str:tema>/subtema/<str:subtema>/asesor/<str:asesor>/hora/<str:hora>',
         nuevaAsesoria, name='nueva_asesoria'),
    path('reportes/', reportes, name='reportes'),
    path('rep-sem/', repSem, name='rep-sem'),
    path('<str:pk>/', detalleAsesoria, name='detalle_asesoria'),
    path('<str:pk>/aceptar/', aceptarAsesoria, name='aceptar_asesoria'),
    path('<str:pk>/cancelar/', cancelarAsesoria, name='cancelar_asesoria'),
    path('<str:pk>/rechazar/', rechazarAsesoria, name='rechazar_asesoria'),
    path('<str:pk>/finalizar/', finalizarAsesoria, name='finalizar_asesoria'),
]

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime as dt

HORAS = [(dt.time(hour=h, minute=m), '{:02d}:{:02d}'.format(h, m)) for h in range(7, 20) for m in [0, 30]]
DIAS = [
    ('0', 'Lunes'),
    ('1', 'Martes'),
    ('2', 'Miércoles'),
    ('3', 'Jueves'),
    ('4', 'Viernes'),
]


class Jefe(models.Model):
    usuario = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    celular = models.CharField(max_length=200, blank=True, null=True)
    clave_empleado = models.CharField(max_length=200, blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        verbose_name = 'Jefe'
        verbose_name_plural = 'Jefes'

    def __str__(self):
        return self.usuario.username


class Departamento(models.Model):
    nombre = models.CharField(max_length=255)
    jefe = models.ForeignKey(Jefe, null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'

    def __str__(self):
        return self.nombre


class Carrera(models.Model):
    nombre = models.CharField(max_length=255)
    departamento = models.ForeignKey(Departamento,
                                     null=True,
                                     blank=True,
                                     on_delete=models.SET_NULL)

    class Meta:
        verbose_name = 'Carrera'
        verbose_name_plural = 'Carreras'

    def __str__(self):
        return self.nombre


class Materia(models.Model):
    nombre = models.CharField(max_length=255, null=False, blank=False)
    competencia = models.TextField(null=True, blank=True)
    clave_materia = models.CharField(max_length=20, null=True, blank=True, unique=True)
    carrera = models.ForeignKey(Carrera, null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ['nombre']
        verbose_name = 'Materia'
        verbose_name_plural = 'Materias'

    def __str__(self):
        return self.nombre


class Asesorado(models.Model):
    usuario = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=255, null=True, blank=True)
    celular = models.CharField(max_length=200, null=True, blank=True)
    carrera = models.ForeignKey(Carrera, null=True, on_delete=models.SET_NULL, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        verbose_name = 'Asesorado'
        verbose_name_plural = 'Asesorados'

    def __str__(self):
        return self.usuario.username


class CatalogoDia(models.Model):
    nombre = models.CharField(null=False, blank=False, max_length=10, choices=DIAS, unique=True)

    class Meta:
        verbose_name = 'Catalogo día'
        verbose_name_plural = 'Catalogo días'

    def __str__(self):
        return self.nombre


class CatalogoHora(models.Model):
    nombre = models.TimeField(null=False, blank=False, max_length=10, choices=HORAS, unique=True)

    class Meta:
        verbose_name = 'Catalogo hora'
        verbose_name_plural = 'Catalogo horas'

    def __str__(self):
        return str(self.nombre)


class Tema(models.Model):
    numero = models.IntegerField(null=False, blank=False)
    nombre = models.CharField(max_length=300, null=False, blank=False)
    competencia = models.TextField(null=False, blank=True)
    materia = models.ForeignKey(Materia, null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = 'Tema'
        verbose_name_plural = 'Temas'

    def __str__(self):
        return self.nombre


class Subtema(models.Model):
    numero = models.IntegerField(null=False, blank=False)
    nombre = models.CharField(max_length=300, null=False, blank=False)
    tema = models.ForeignKey(Tema, null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = 'Subtema'
        verbose_name_plural = 'Subtemas'

    def __str__(self):
        return self.nombre


class Asesor(models.Model):
    usuario = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=255, null=True, blank=False)
    celular = models.CharField(max_length=200, null=True, blank=True)
    clave_empleado = models.CharField(max_length=200, null=True, blank=True)
    lugar_asesoria = models.CharField(max_length=300, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    departamento = models.ForeignKey(Departamento, null=True, on_delete=models.SET_NULL, blank=False)
    subtetmas = models.ManyToManyField(Subtema, through='TemarioAsesor')
    horarios = models.ManyToManyField(CatalogoDia, through='Agenda')

    class Meta:
        verbose_name = 'Asesor'
        verbose_name_plural = 'Asesores'

    def __str__(self):
        return self.usuario.username


class Agenda(models.Model):
    asesor = models.ForeignKey(Asesor, null=False, on_delete=models.CASCADE)
    dia = models.ForeignKey(CatalogoDia, null=True, blank=True, on_delete=models.SET_NULL, choices=DIAS)
    hora = models.ForeignKey(CatalogoHora, null=True, blank=True, on_delete=models.SET_NULL, choices=HORAS)
    disponible = models.BooleanField('Disponible/no disponible', default=True, null=True, blank=True)

    class Meta:
        ordering = ['asesor', 'dia', 'hora']
        verbose_name = 'Agenda'
        verbose_name_plural = 'Agendas'
        unique_together = (('asesor', 'dia', 'hora'),)


class TemarioAsesor(models.Model):
    materia = models.ForeignKey(Materia, null=False, blank=False, on_delete=models.CASCADE)
    tema = models.ForeignKey(Tema, null=False, blank=False, on_delete=models.CASCADE)
    subtema = models.ForeignKey(Subtema, null=False, blank=False, on_delete=models.CASCADE)
    asesor = models.ForeignKey(Asesor, null=False, blank=False, on_delete=models.CASCADE)
    activo = models.BooleanField('Activo/no activo', default=False)

    class Meta:
        verbose_name = 'Temario del asesor'
        verbose_name_plural = 'Temarios del asesor'
        unique_together = (('materia', 'tema', 'subtema', 'asesor'),)

    def __str__(self):
        return self.materia.nombre

apps/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django import forms
from django.utils.translation import gettext, gettext_lazy as _
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from .models import Asesorado, Asesor, Agenda

from django.utils.dateparse import parse_time
import datetime as dt


HORAS = [(dt.time(hour=h, minute=m), '{:02d}:{:02d}'.format(h, m)) for h in range(7, 20) for m in [0, 30]]
DIAS = [
    ('0', 'Lunes'),
    ('1', 'Martes'),
    ('2', 'Miércoles'),
    ('3', 'Jueves'),
    ('4', 'Viernes'),
]


class AgendaForm(ModelForm):
    error_messages = {
        'wrong_time': _('La hora de inicio debe ser menor a la de final.'),
    }
    dia_semana = forms.CharField(widget=forms.Select(choices=DIAS))
    hora_inicio = forms.TimeField(widget=forms.Select(choices=HORAS))
    hora_final = forms.TimeField(widget=forms.Select(choices=HORAS))

    class Meta:
        model = Agenda
        fields = ['dia_semana', 'hora_inicio', 'hora_final']

    def clean(self):
        cleaned_data = self.cleaned_data
        hora_inicio = self.cleaned_data.get('hora_inicio')
        hora_final = self.cleaned_data.get('hora_final')
        if hora_inicio >= hora_final:
            raise ValidationError(
                self.error_messages['wrong_time'],
                code='wrong_time',
            )
        else:
            return cleaned_data


class AsesoradoForm(ModelForm):
    class Meta:
        model = Asesorado
        fields = ['celular', 'nombre', 'carrera']


class AsesorForm(ModelForm):
    class Meta:
        model = Asesor
        fields = ['celular', 'nombre', 'departamento', 'clave_empleado', 'lugar_asesoria']


class CreateUserForm(UserCreationForm):
    error_messages = {
        'password_mismatch': _('The two password fields didn’t match.'),
        'bad_domain': _('El dominio permitido es colima.tecnm.mx .'),
        'user_exists': _('El usuario ya se encuentra registrado.'),
        'user_student_incorrect': _('El correo del alumno esta formado por 8 dígitos mas el dominio.'),
    }

    email = forms.EmailField(
        required=True,
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={'autocomplete': 'email'})
    )

    class Meta:
        model = User
        fields = ('email',)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email:
            user, domain = email.split('@')
            if domain != 'colima.tecnm.mx':
                raise ValidationError(
                    self.error_messages['bad_domain'],
                    code='bad_domain',
                )
            if User.objects.filter(username=email).exists():
                raise ValidationError(
                    self.error_messages['user_exists'],
                    code='user_exists',
                )
            if user.isdigit() and len(user) != 8:
                raise ValidationError(
                    self.error_messages['user_student_incorrect'],
                    code='user_student_incorrect',
                )
        return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        user.username = self.cleaned_data["email"]
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

templates/accounts/agendar.html
{% include 'accounts/nav.html' %}

{% block content %}


<main class="container">
    <!---Titulo-->
  <div class="row">
    <div class="col">
      <h1 id="title" class="my-3"><a href="#"><i class="fas fa-arrow-circle-left px-4"></i></a> Agendar asesoría</h1>
    </div>
  </div>


  <div class="container text-center">
    <div class="row">
        <div class="col-12">
          <!-- Obvi esta parte no sera asi, pero es para ver si visualmente quedaria asi -->
          <select class="browser-default custom-select my-5">
            <option selected>Selecciona la carrera</option>
            <option value="1">Ingenieria en Sistemas Computacionales</option>
            <option value="2">Informatica</option>
          </select>
        </div>
    </div>
  
    <div class="row">
        <div class="col-12">
          <!-- Mostrar las materias de acuerdo a su kardex-->
          <select class="browser-default custom-select mb-5">
            <option selected>Materia</option>
            <option value="1">Calculo Diferencial</option>
            <option value="2">Fundamentos de programacion</option>
            <option value="3">Matematicas discretas</option>
            <option value="4">Calculo Integral</option>
          </select>
        </div>
    </div>
    
    <div class="row">
        <div class="col-12">
          <select class="browser-default custom-select mb-5">
            <option selected>Tema (unidad)</option>
            <option value="1">Numeros Reales</option>
            <option value="2">Funciones</option>
            <option value="3">Limites y continuidad</option>
            <option value="4">Derivadas</option>
            <option value="5">Aplicaciones de las derivadas</option>
          </select>
        </div>
    </div>
  
    <div class="row">
      <div class="col-12">
        <select class="browser-default custom-select mb-5">
          <option selected>Subtema</option>
          <option value="1">Los numeros reales</option>
          <option value="2">Axiomas de los números reales.</option>
          <option value="3">Intervalos y su representación gráfica.</option>
          <option value="4">Valor absoluto y sus propiedades.</option>
          <option value="5">Propiedades de las desigualdades.</option>
          <option value="6">Resolución de desigualdades de primer y segundo grado con una incógnita.</option>
          <option value="6">Resolución de desigualdades que incluyan valor absoluto. </option>
        </select>
      </div>
    </div>
    <div> 
      <button class="small my-btn">Buscar</button> 
    </div>
  </div>

</main>


<!-- The result window -->
<div id="agenda" class="result">

  <div>
    <button class="my-btn"><i class="fas fa-chevron-right"></i></button>
    <p>fechas</p>
    <button class="my-btn"><i class="fas fa-chevron-left"></i></button>
  </div>

  <div class="modal-content">
    <span class="close">&times;</span>
    <table class="table table-hover">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Asesor</th>
          <th scope="col">Lunes</th>
          <th scope="col">Martes</th>
          <th scope="col">Miercoles</th>
          <th scope="col">Jueves</th>
          <th scope="col">Viernes</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">Octavio Paz</th>
          <td>13:00</td>
          <td>11:00</td>
          <td></td>
          <td>13:00</td>
          <td></td>
        </tr>
        <tr>
          <th scope="row">Jose Sonora</th>
          <td>14:00</td>
          <td></td>
          <td>10:00</td>
          <td>9:00</td>
          <td>11:00</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>


{% endblock %}

templates/accounts/horario.html
{% include 'root.html' %}
{% load widget_tweaks %}

{% block content %}


<main class="container">
    
    <div class="row">
        <div class="col">
            <h1 id="title" class="my-3"><a href="{% url 'accounts:principal' %}"><i class="icon fas fa-arrow-circle-left px-4"></i></a>Horario</h1>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col">
            <p class="text-secondary">Este es el horario de atención semanal para las asesorías, sus bloques se dividen en lapsos de 30 minutos. Para eliminarlos de click a la X azul.
            </p>
        </div>
    </div>

    <div class="row my-4">
        <div class="col">
            <form class="form-inline" method="POST" action="">
                <div>
                {% csrf_token %}
                {% render_field form.dia_semana class="form-control" %}
                <p class="lapso">De</p>
                {% render_field form.hora_inicio class="form-control" %}
                <p class="lapso">a</p>
                {% render_field form.hora_final class="form-control" %}
                <input type="submit" class = "btn my-btn small m-4" value="Agregar bloque">
                </div>
            </form>
        </div>
    </div>

    <hr class="rounded">

    <div class="row my-5 justify-content-around">
        {% for dia in dias %}
            <div class="col-md-2">
                <div class="card text-center">
                    <div class="card-header">
                        <strong>{{dia}}</strong>
                    </div>
                    <ul class="list-group list-group-flush">
                        {% for agenda in agendas %}
                            {% if agenda.dia.get_nombre_display == dia %}
                                <li class="list-group-item">
                                    {{agenda.hora.get_nombre_display}}
                                    <a href="{% url 'accounts:eliminar_horario' agenda.id %}" title="Borrar">x</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endfor %}
        </div>

</main>



{% endblock %}

templates/accounts/ingreso.html
{% extends 'root.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<main class="container text-center">


    <div class="row pt-3">
        <div class="col"><a href="{% url 'accounts:ingreso' %}"><img src="{% static 'images/LogoP.png' %}" width="280" height="140" alt="Wass logo"></a></div>
    </div>

    <div class="row pt-5 pb-4">
        <div class="col">
            <h2 class="font-weight-bold">Iniciar Sesión</h2>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col">

                <form method="POST" action="">
                    <!--- Inputs y boton -->
                    {% csrf_token %}
                    <input name="username" type="text" class="form-control form-control-lg input-box mb-4"
                        aria-describedby="user" placeholder="Usuario" required="required">
                    <input name="password" type="password" class="form-control form-control-lg input-box mb-5"
                        placeholder="Contraseña" required="required">
                    <input type="submit" class="small my-btn mb-1 waves-effect" value="Entrar">
                    <a class="text-muted mb-4" href="{% url 'accounts:reset_password' %}">Olvidé mi contraseña</a>
                </form>

                <p class="font-italic"><a href="{% url 'accounts:registro' %}" class="text-decoration-none"
                        style="display:inline;">Registrarse</a> en caso de no tener una cuenta</p>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <p>
                    <a data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample" >
                        <i class="help-icon fas fa-info-circle"></i>
                    </a>
                </p>
    
                <div class="collapse" id="collapseExample">
                    <div class="card border-light bg-light ">
                        <div class="card-body float">
                            WASS es una plataforma de asesorias sistematizada que te permite agendar con un docente de manera remota en el Tecnologico Nacional de Mexico Campus Colima.
                        </div>
                    </div>
                </div>
    
            </div>
        </div>
    </div>

</main>

<!--Boton de Informacion-->
<div class="container">

</div>

{% endblock %}

templates/accounts/materia_list.html
{% include 'root.html' %}
{% load widget_tweaks %}
{% block content %}


{% for materia in object_list %}
    <li>{{ materia.nombre }}</li>
    
{% endfor %}
{% endblock %}

templates/accounts/reportes.html
{% include 'root.html' %}

{% block content %}


<main class="container">

    <div class="container text-center mt-5">
        <!-- Ver reportes de asesorias tomadas por semestre -->
        <div class="row">
            <div class="col">
                <a href={% url 'accounts:rep-sem' %}><button type="button" class="my-btn big">Asesorías por semestre</button></a>
            </div>
        </div>
    </div>

</main>

{% endblock %}

templates/accounts/simple-nav.html
{% extends 'root.html' %}

{% load static %}


    {% block content %}

    <nav class="navbar navbar-dark bg-dark">
        <img src="{% static 'images/Logo.png' %}" class="ml-3" width="75" height="40" loading="lazy" alt="Wass logo">
    </nav>

    {% endblock %}

templates/accounts/temario.html
{% include 'root.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}


<main class="container">

    <div class="container">
        <p class="text-secondary">A continuación se muestra la lista de materias a las que usted está dispuesto a
            asesorar. Puede seleccionar qué temas en particular desea poder brindar asesoría.
        </p>

        {% if materias %}
        <table class="table table-hover table-responsive-sm my-5">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Clave</th>
                    <th scope="col">Materia</th>
                    <th scope="col">Acción</th>
                </tr>
            </thead>
            <tbody>
                {% for materia in materias %}
                <tr>
                    <th scope="row">{{materia.materia.clave_materia}}</th>
                    <td>{{ materia.materia.nombre }}</td>
                    <td>
                        <a href="{% url 'accounts:temario_materia_editar' materia.materia.id %}"
                            class="btn btn-warning mr-3 mb-3" title="Seleccione los temas a asesorar.">Editar</a>
                        <a href="{% url 'accounts:temario_eliminar' materia.materia.id %}" class="btn btn-danger mb-3"
                            title="Quitar esta materia de mi temario.">Eliminar</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>

    <hr class="rounded">

    <div class="container">
        <div class="row text-center my-3">
            <div class="col my-4">
                <h2>Agregar materia</h2>
            </div>
        </div>

        <p class="text-secondary">
            Busque la materia por nombre o clave. Para ver todas las materias de su Departamento presione directamente
            en el boton "Buscar".
        </p>
        <form class="form-row align-items-center" method='GET' action="/temario/agregar/">
            <div class="col-8">
                {% render_field filtro.form.query class="form-control" placeholder="Nombre o clave de materia" %}
            </div>
            <div class="col-auto my-4">
                <button id="search" class="my-btn smaller" type="submit">Buscar</button>
            </div>
        </form>
    </div>

</main>

{% endblock %}

templates/accounts/temario_eliminar.html
{% include 'root.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<main class="container text-center">
    
    <div class="row mt-3">
        <div class="col mt-3">
            <form action="" method="post">
                {% csrf_token %}
                <h2 class="mb-4">¿Está seguro de eliminar la materia "{{materia.nombre}}" de sus asesorias?</h2>
                <div class="text-center">
                    <input type="submit" value="Eliminar" class="btn btn-lg btn-warning mx-3">
                    <a href="{% url 'accounts:temario'%}" class="btn btn-lg my-btn mx-3">Cancelar</a>
                </div>
            </form>
        </div>
    </div>

</main>

{% endblock %}

templates/accounts/temario_materia.html
{% include 'root.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<main class="container">

    <div class="container text-center">
        <form method='GET' action="/temario/agregar/">
            <div class="form-row align-items-center">
                <div class="col-8">
                    {% render_field filtro.form.query class="form-control" placeholder="Nombre o clave de materia" %}
                </div>
                <div class="col-auto my-3">
                    <button class="my-btn smaller" type="submit">Buscar</button>
                </div>
            </div>
        </form>
    </div>

    <div class="container mt-3 scroll">
        {% if materias %}
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Clave</th>
                    <th scope="col">Materia</th>
                    <th scope="col">Acción</th>
                </tr>
            </thead>
            <tbody>
                {% for materia in materias %}
                <tr>
                    <th scope="row">{{materia.clave_materia}}</th>
                    <td>{{ materia.nombre }}</td>
                    <td>
                        <a href="{% url 'accounts:temario_agregar' materia.id %}">
                            <button title="Agregar esta materia a mi temario" class="btn btn-success">Agregar</button>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p class="note-empty"> No se encontraron resultados a la búsqueda</p>
        {% endif %}
    </div>

</main>

{% endblock %}

templates/accounts/temario_temas.html
{% include 'root.html' %}
{% load static %}

{% block content %}
<main class="container">

    <div class="row">
        <div class="col my-3">
            <p class="text-secondary">Marque la casilla de aquellos temas y/o subtemas que quiera 
                <b>especificar para dar asesoria.</b>
            </p>
        </div>
    </div>

    <div class="row">
        {% if temas %}
        <form action="" method="post" class="container">
        {% csrf_token %}
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">No.</th>
                        <th scope="col">Tema - Subtema</th>
                        <th scope="col">Activo</th>
                    </tr>
                </thead>
                <tbody>
                    {% for tema in temas %}

                        {% if tema.subtema.numero == 1 %}
                            <tr>
                                <th>{{tema.tema.numero}}</th>
                                <th>{{ tema.tema.nombre}}</th>
                                <th><input type="checkbox" name="tema_{{ tema.tema.numero }}" class="select_all"></th>
                            <tr>
                        {% endif %}

                        <tr>
                            <td>{{ tema.tema.numero }}.{{ tema.subtema.numero}} </td>
                            <td>{{ tema.subtema.nombre }}</td>
                            {% if tema.activo %}
                            <td><input type="checkbox" checked="checked" name="{{tema.id}}" class="tema_{{tema.tema.numero}}"></td>
                            {% else %}
                            <td><input type="checkbox" name="{{tema.id}}" class="tema_{{tema.tema.numero}}"></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="my-4 text-center">
            <a href="{% url 'accounts:temario' %}" class="btn btn-secondary small">Cancelar</a>
            <input type="submit" value="Actualizar" class="btn my-btn small">
            </div>
        </form>
        {% else %}
        <p> No se encontraron resultados a la búsqueda</p>
        {% endif %}
    </div>

</main>
{% endblock %}

templates/accounts/temas.html
{% include 'root.html' %}

{% block content %}

temas

{% endblock %}