app/urls.py
from django.contrib import admin
from django.urls import path, include
import os

urlpatterns = [
    path('', include(('accounts.urls', 'accounts'))),
    path('asesoria/', include(('asesoria.urls', 'asesoria'))),
    path('admin/', admin.site.urls),
]

apps/accounts/urls.py
from django.urls import path, reverse_lazy
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_vies
from .views import ListarMaterias
from . import views


app_name = 'accounts'
urlpatterns = [
    path('', views.principal, name='principal'),
    path('registro/', views.registro, name='registro'),
    path('ingreso/', views.ingreso, name='ingreso'),
    path('salir/', views.salir, name='salir'),
    path('configurar/', views.configurar, name='configurar'),
    path('configurar/contrasena/', views.contrasena, name='contrasena'),
    path('configurar/horario/', views.horario, name='horario'),
    path('configurar/horario/eliminar/<str:pk>/', views.eliminarHorario, name='eliminar_horario'),
    path('contrasena_restablecer/',
         auth_vies.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done'),
                                             extra_context={'hide_logout': True, 'hide_config': True}),
         name='reset_password'),
    path('contrasena_restablecer_enviar/', auth_vies.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('contrasena_restablecer/<uidb64>/<token>/', auth_vies.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('contrasena_restablecer_terminado/',
         auth_vies.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('materia/', ListarMaterias.as_view(), name='listar_materias'),
    path('temario/', views.temario, name='temario'),
    path('temario/materia/<str:pk>', views.temarioMateriaEditar, name='temario_materia_editar'),
    path('temario/agregar/', views.temarioAgregarModal, name='temario_agregar_modal'),
    path('temario/agregar/<str:pk>/', views.temarioAgregar, name='temario_agregar'),
    path('temario/eliminar/<str:pk>/', views.temarioEliminar, name='temario_eliminar'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/asesoria/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', verAsesorias, name='ver_asesorias'),
    path('materia/', seleccionMateria, name='seleccion_materia'),
    path('materia/<str:materia>/tema/', seleccionTema, name='seleccion_tema'),
    path('materia/<str:materia>/tema/<str:tema>/subtema/',
         seleccionSubtema, name='seleccion_subtema'),
    path('materia/<str:materia>/tema/<str:tema>/subtema/<str:subtema>/asesor/',
         seleccionAsesor, name='seleccion_asesor'),
    path('materia/<str:materia>/tema/<str:tema>/subtema/<str:subtema>/asesor/<str:asesor>/hora/<str:hora>',
         nuevaAsesoria, name='nueva_asesoria'),
    path('reportes/', reportes, name='reportes'),
    path('rep-sem/', repSem, name='rep-sem'),
    path('<str:pk>/', detalleAsesoria, name='detalle_asesoria'),
    path('<str:pk>/aceptar/', aceptarAsesoria, name='aceptar_asesoria'),
    path('<str:pk>/cancelar/', cancelarAsesoria, name='cancelar_asesoria'),
    path('<str:pk>/rechazar/', rechazarAsesoria, name='rechazar_asesoria'),
    path('<str:pk>/finalizar/', finalizarAsesoria, name='finalizar_asesoria'),
]

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime as dt

HORAS = [(dt.time(hour=h, minute=m), '{:02d}:{:02d}'.format(h, m)) for h in range(7, 20) for m in [0, 30]]
DIAS = [
    ('0', 'Lunes'),
    ('1', 'Martes'),
    ('2', 'Miércoles'),
    ('3', 'Jueves'),
    ('4', 'Viernes'),
]


class Jefe(models.Model):
    usuario = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    celular = models.CharField(max_length=200, blank=True, null=True)
    clave_empleado = models.CharField(max_length=200, blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        verbose_name = 'Jefe'
        verbose_name_plural = 'Jefes'

    def __str__(self):
        return self.usuario.username


class Departamento(models.Model):
    nombre = models.CharField(max_length=255)
    jefe = models.ForeignKey(Jefe, null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'

    def __str__(self):
        return self.nombre


class Carrera(models.Model):
    nombre = models.CharField(max_length=255)
    departamento = models.ForeignKey(Departamento,
                                     null=True,
                                     blank=True,
                                     on_delete=models.SET_NULL)

    class Meta:
        verbose_name = 'Carrera'
        verbose_name_plural = 'Carreras'

    def __str__(self):
        return self.nombre


class Materia(models.Model):
    nombre = models.CharField(max_length=255, null=False, blank=False)
    competencia = models.TextField(null=True, blank=True)
    clave_materia = models.CharField(max_length=20, null=True, blank=True, unique=True)
    carrera = models.ForeignKey(Carrera, null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ['nombre']
        verbose_name = 'Materia'
        verbose_name_plural = 'Materias'

    def __str__(self):
        return self.nombre


class Asesorado(models.Model):
    usuario = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=255, null=True, blank=True)
    celular = models.CharField(max_length=200, null=True, blank=True)
    carrera = models.ForeignKey(Carrera, null=True, on_delete=models.SET_NULL, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        verbose_name = 'Asesorado'
        verbose_name_plural = 'Asesorados'

    def __str__(self):
        return self.usuario.username


class CatalogoDia(models.Model):
    nombre = models.CharField(null=False, blank=False, max_length=10, choices=DIAS, unique=True)

    class Meta:
        verbose_name = 'Catalogo día'
        verbose_name_plural = 'Catalogo días'

    def __str__(self):
        return self.nombre


class CatalogoHora(models.Model):
    nombre = models.TimeField(null=False, blank=False, max_length=10, choices=HORAS, unique=True)

    class Meta:
        verbose_name = 'Catalogo hora'
        verbose_name_plural = 'Catalogo horas'

    def __str__(self):
        return str(self.nombre)


class Tema(models.Model):
    numero = models.IntegerField(null=False, blank=False)
    nombre = models.CharField(max_length=300, null=False, blank=False)
    competencia = models.TextField(null=False, blank=True)
    materia = models.ForeignKey(Materia, null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = 'Tema'
        verbose_name_plural = 'Temas'

    def __str__(self):
        return self.nombre


class Subtema(models.Model):
    numero = models.IntegerField(null=False, blank=False)
    nombre = models.CharField(max_length=300, null=False, blank=False)
    tema = models.ForeignKey(Tema, null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = 'Subtema'
        verbose_name_plural = 'Subtemas'

    def __str__(self):
        return self.nombre


class Asesor(models.Model):
    usuario = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=255, null=True, blank=False)
    celular = models.CharField(max_length=200, null=True, blank=True)
    clave_empleado = models.CharField(max_length=200, null=True, blank=True)
    lugar_asesoria = models.CharField(max_length=300, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    departamento = models.ForeignKey(Departamento, null=True, on_delete=models.SET_NULL, blank=False)
    subtetmas = models.ManyToManyField(Subtema, through='TemarioAsesor')
    horarios = models.ManyToManyField(CatalogoDia, through='Agenda')

    class Meta:
        verbose_name = 'Asesor'
        verbose_name_plural = 'Asesores'

    def __str__(self):
        return self.usuario.username


class Agenda(models.Model):
    asesor = models.ForeignKey(Asesor, null=False, on_delete=models.CASCADE)
    dia = models.ForeignKey(CatalogoDia, null=True, blank=True, on_delete=models.SET_NULL, choices=DIAS)
    hora = models.ForeignKey(CatalogoHora, null=True, blank=True, on_delete=models.SET_NULL, choices=HORAS)
    disponible = models.BooleanField('Disponible/no disponible', default=True, null=True, blank=True)

    class Meta:
        ordering = ['asesor', 'dia', 'hora']
        verbose_name = 'Agenda'
        verbose_name_plural = 'Agendas'
        unique_together = (('asesor', 'dia', 'hora'),)


class TemarioAsesor(models.Model):
    materia = models.ForeignKey(Materia, null=False, blank=False, on_delete=models.CASCADE)
    tema = models.ForeignKey(Tema, null=False, blank=False, on_delete=models.CASCADE)
    subtema = models.ForeignKey(Subtema, null=False, blank=False, on_delete=models.CASCADE)
    asesor = models.ForeignKey(Asesor, null=False, blank=False, on_delete=models.CASCADE)
    activo = models.BooleanField('Activo/no activo', default=False)

    class Meta:
        verbose_name = 'Temario del asesor'
        verbose_name_plural = 'Temarios del asesor'
        unique_together = (('materia', 'tema', 'subtema', 'asesor'),)

    def __str__(self):
        return self.materia.nombre

apps/asesoria/models.py
from django.db import models
from accounts.models import Asesorado, Asesor, Subtema

ESTADOS_ASESORIA = [
    ('pendiente', 'Pendiente'),
    ('aceptada', 'Aceptada'),
    ('rechazada', 'Rechazada'),
    ('cancelada', 'Cancelada'),
    ('finalizada', 'Finalizada'),
]


class Asesoria(models.Model):
    fecha_solicitud = models.DateTimeField(auto_now_add=True, null=False)
    fecha_asesoria = models.DateTimeField('Fecha asesoría', null=False)
    estado = models.CharField('Estado actual', max_length=45, choices=ESTADOS_ASESORIA, default='pendiente')
    descripcion = models.TextField('Descripción', null=True, blank=False)
    requisitos = models.TextField('Requisitos previos a la asesoría', null=True, blank=True)
    comentario_finalizada = models.TextField('Comentarios: asesoría finalizada', null=True, blank=False)
    razon_cancelada = models.TextField('Razón de cancelación', null=True, blank=False)
    razon_rechazada = models.TextField('Razón de rechazo', null=True, blank=False)
    asesorado = models.ForeignKey(Asesorado, null=False, on_delete=models.PROTECT)
    asesor = models.ForeignKey(Asesor, null=False, on_delete=models.PROTECT)
    subtema = models.ForeignKey(Subtema, null=False, on_delete=models.PROTECT)
    agenda = models.IntegerField()

    class Meta:
        verbose_name = 'Asesoria'
        verbose_name_plural = 'Asesorias'

    def __str__(self):
        return str(self.id)

apps/asesoria/forms.py
from django.forms import ModelForm
from django import forms
from asesoria.models import Asesoria


class SolicitudAseroriaForm(ModelForm):
    class Meta:
        model = Asesoria
        fields = ['descripcion']


class DetalleAseroriaForm(ModelForm):
    class Meta:
        model = Asesoria
        fields = ['descripcion', 'requisitos', 'razon_cancelada', 'razon_rechazada', 'comentario_finalizada']


class CancelacionAsesoriaForm(ModelForm):

    class Meta:
        model = Asesoria
        fields = ['razon_cancelada']


class AceptarAsesoriaForm(ModelForm):
    class Meta:
        model = Asesoria
        fields = ['requisitos']


class FinalizarAsesoriaForm(ModelForm):
    class Meta:
        model = Asesoria
        fields = ['comentario_finalizada']


class RechazarAsesoriaForm(ModelForm):
    class Meta:
        model = Asesoria
        fields = ['razon_rechazada']

templates/asesoria/confirmar_asesoria.html
{% include 'root.html' %}
{% load static %}
{% load widget_tweaks %}

{% load auth_extras %}

{% block content %}

<main class="container">

    <div class="row my-3">
        <div class="col pl-4">
          <p class="text-secondary">Verifique la información y en caso de ser necesario, añada los datos faltantes.</p>
        </div> 
      </div>
      
    <div class="card container m-6 bg-light my-3"> 
        <div class="row">
            <div class="col my-3 text-center">
                <h4 class="text-muted">Detalles de la asesoría</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 text-center m-auto">
                <img src="{% static 'images/user.svg' %}" width="75" alt="foto de perfil">
            </div>
            <div class="col">
                <ul class="info">
                    <li>{% if request.user|has_group:"asesorados" %}
                        <strong>Asesor:</strong>   
                            {% if asesoria.asesor.nombre %}
                                {{asesoria.asesor.nombre}}
                                {% else %}
                                {{asesoria.asesor}}
                            {% endif %}
                        {% else %}
                        <strong>Alumno:</strong> {{asesoria.asesorado.nombre}}
                        {% endif %}
                    </li>
                    <li><strong>Tema:</strong> {{ asesoria.subtema.nombre }}</li>
                    <li><strong>Lugar:</strong>
                        {% if asesoria.asesor.lugar_asesoria %}
                        {{asesoria.asesor.lugar_asesoria}}
                        {% else %}
                        Acordar con el asesor.
                        {% endif %}
                    </li>
                    {% if asesoria.fecha_solicitud %}
                        <li><strong>Fecha de solicitud:</strong> {{ asesoria.fecha_solicitud|date:"l d M Y" }} {{ asesoria.fecha_solicitud|time:"H:i" }}</li>
                    {% endif %}
                    <li><strong>Fecha de asesoría:</strong> {{ asesoria.fecha_asesoria|date:"l d M Y" }} {{ asesoria.fecha_asesoria|time:"H:i" }}</li>
                </ul>
            </div>
        </div>
    

    {% if entrada %}
    <div class="row m-3">
        <div class="col mt-3">
            <form method="post" action="">
                {% csrf_token %}
                <div class="form-group">
                    <label class="lead" for="razones">{{ entrada }}</label>
                    {% if form.comentario_finalizada %}
                    {% render_field form.comentario_finalizada class="form-control" rows="3" %}
                    {% endif %}
                    {% if form.razon_cancelada %}
                    {% render_field form.razon_cancelada class="form-control" rows="3" %}
                    {% endif %}
                    {% if form.razon_rechazada %}
                    {% render_field form.razon_rechazada class="form-control" rows="3" %}
                    {% endif %}
                    {% if form.descripcion %}
                    {% render_field form.descripcion class="form-control" rows="3" %}
                    {% endif %}
                    {% if form.requisitos %}
                    {% render_field form.requisitos class="form-control" rows="3" %}
                    {% endif %}
                    <div class="text-center">
                        <button type="submit" class="my-btn smaller mt-3">Confirmar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    {% else %}
        {% if asesoria.descripcion %}
        <div class="container m-6 bg-light">
            <div class="row">
                <div class="col mt-3">
                    <h4>Descripción de la asesoría</h4>
                    <p>{{ asesoria.descripcion }}</p>
                </div>
            </div>
        </div>
        {% endif %}
        {% if asesoria.requisitos %}
        <div class="container m-6 bg-light">
            <div class="row">
                <div class="col mt-3">
                    <h4>Requisitos previos a la asesoría</h4>
                    <p>{{ asesoria.requisitos }}</p>
                </div>
            </div>
        </div>
        {% endif %}
        {% if asesoria.razon_cancelada %}
        <div class="container m-6 bg-light">
            <div class="row">
            	<div class="col mt-3">
            	    <h4>Razón de cancelación</h4>
            	    <p>{{ asesoria.razon_cancelada }}</p>
            	</div>
            </div>
        </div>
        {% endif %}
        {% if asesoria.razon_rechazada %}
        <div class="container m-6 bg-light">
            <div class="row">
                <div class="col mt-3">
                    <h4>Razón de rechazo</h4>
                    <p>{{ asesoria.razon_rechazada }}</p>
                </div>
            </div>
        </div>
        {% endif %}
        {% if asesoria.comentario_finalizada %}
        <div class="container m-6 bg-light">
            <div class="row">
                <div class="col mt-3">
                    <h4>Comentario final</h4>
                    <p>{{ asesoria.comentario_finalizada }}</p>
                </div>
            </div>
        </div>
        {% endif %}
    {% endif %}
    </div>
</main>


{% endblock %}

templates/asesoria/notificacion_email.html
Notificación: {{accion}} de asesoría.
Asesorado: {{asesoria.asesorado.nombre}}
Asesor: {{asesoria.asesor.nombre}}

Fecha: {{ asesoria.fecha_asesoria|date:"l d M Y" }} {{ asesoria.fecha_asesoria|time:"H:i" }}
Subtema: {{ asesoria.subtema.nombre }}

{% if asesoria.descripcion %}
Descripción de asesoría: {{asesoria.descripcion}}
{% endif %}

{% if asesoria.requisitos %}
Requsitos para la asesoría: {{asesoria.requisitos}}
{% endif %}

{% if asesoria.comentario_finalizada %}
Comentario final: {{asesoria.comentario_finalizada}}
{% endif %}

{% if asesoria.razon_cancelada %}
Razón de cancelación: {{asesoria.razon_cancelada}}
{% endif %}

{% if asesoria.razon_rechazada %}
Razón de rechazo: {{asesoria.razon_rechazada}}
{% endif %}

templates/asesoria/nueva_asesoria.html
{% include 'root.html' %}
{% load widget_tweaks %}
{% block content %}


<main class="container">
  <form class="container" method="POST" action="">
    {% csrf_token %}

    <label for="fecha_asesoria">{{form.fecha_asesoria.label}}</label>
    {% render_field form.fecha_asesoria|append_attr:"readonly" class="form-control" %}
    {% render_field form.subtema_nombre|append_attr:"readonly" class="form-control" %}
    {% render_field form.asesor_nombre|append_attr:"readonly" class="form-control" %}
    {% render_field form.descripcion %}
  <br>¿Desea confirmar la siguiente asesoria? <br>
    <a href="{% url 'accounts:principal'%}" class="small my-btn">Cancelar</a>
    <input type="submit" class="small my-btn" value="Confirmar">
  </form>




  {% endblock %}

templates/asesoria/rep-sem.html
{% include 'root.html' %}
{% load widget_tweaks %}
{% load auth_extras %}
{% load static %}

{% block content %}
<main class="container">
{% if asesorias %}
  <table class="my-table table table-striped table-hover">
    <thead>
      <tr>
        <th scope="col">
          {% if request.user|has_group:"asesorados" %}
          Asesor
          {% else %}
          Alumno
          {% endif %}
        </th>
        <th scope="col">Tema</th>
        <th scope="col">Fecha</th>
        <th scope="col">Estado</th>
      </tr>
    </thead>
    <tbody>
      {% for asesoria in asesorias %}
      <tr class="clickable-row" data-href="{% url 'asesoria:detalle_asesoria' asesoria.id %}">
        <td>
          {% if request.user|has_group:"asesorados" %}
          {{asesoria.asesor.nombre}}
          {% else %}
          {{asesoria.asesorado.nombre}}
          {% endif %}
        </td>
        <th scope="row">{{ asesoria.subtema }}</th>
        <td>{{ asesoria.fecha_asesoria.date }}</td>
        <td>{{ asesoria.get_estado_display }}</td>
      </tr>
      {% endfor %}

    </tbody>
  </table>
{% endif %}

</main>

<script>
  jQuery(document).ready(function($) {

      $(".clickable-row").click(function() {

          window.location = $(this).data("href");
      

      });

    $("#container").on('click-row.bs.table', function (e, row, $element) {
      
      window.location = $element.data('href');

    });
  });

</script>


{% endblock %}

templates/asesoria/seleccion_asesor.html
{% include 'root.html' %}

{% block content %}

<main class="container">
  
<!-- Hacer que aparezca esta instruccion solo cuando si haya asesores -->
  <div class="row my-3">
    <div class="col pl-4">
      <p class="text-secondary">A continuación se muestran los asesores disponibles, seleccione en alguno para visualizar su horario.</p>
    </div> 
  </div>
  
  <div id="accordion" class="container text-center">

  {% for asesor in asesores %}

      <div class="card text-center">
        <div class="card-header text-white bg-dark border-light">
          <a data-toggle="collapse" href="#collapse{{asesor.id}}" aria-expanded="true" aria-controls="collapse-example" 
          id="{{asesor.id}}" class="text-white">
            <strong>
              {% if asesor.asesor.nombre %}
              {{asesor.asesor.nombre}}
              {% else %}
              {{asesor.asesor}}
              {% endif %}
            </strong>
          </a>
          
        </div>
        <div id="collapse{{asesor.id}}" class="collapse" aria-labelledby="{{asesor.asesor.id}}" data-parent="#accordion">
          <ul class="list-group list-group-flush">
            {% for agenda in agendas %}
            {% if asesor.asesor == agenda.asesor %}
            <a href="{% url 'asesoria:nueva_asesoria' materia tema subtema asesor.asesor.id agenda.id %}">
              <li class="list-group-item">
                {{agenda.dia.get_nombre_display}} {{agenda.hora.get_nombre_display}}
              </li>
            </a>
            {% endif %}
            {% endfor %}
          </ul>
        </div>
      </div> 
      
  {% endfor %}

  </div>
</main>

{% endblock %}

templates/asesoria/seleccion_materia.html
{% include 'root.html' %}

{% block content %}

<main class="container">
  <!-- DEBE regresar a principal. -->
  <div class="row">
    <div class="col">
        <h1 id="title" class="my-3"><a href="{% url 'accounts:principal' %}"><i class="icon fas fa-arrow-circle-left pr-4"></i></a>Selección de Materia</h1>
    </div>
  </div>

    <div class="row my-3">
      <div class="col">
        <p class="text-secondary"><strong>Paso 1.</strong> Elija la materia a la cual pertenezca su tema para asesorar.</p>
      </div>
    </div>

    <div class="card text-center scroll text-white bg-dark border-light">
      <div class="card-header ">
        <strong>{{carrera}}</strong>
      </div>
      <ul class="list-group list-group-flush">
        {% for materia in materias %}
        <a href="{% url 'asesoria:seleccion_tema' materia.id %}">
          <li class="list-group-item my-list">
            {{materia.nombre}}
          </li>
        </a>
        {% endfor %}
      </ul>
    </div>

</main>

{% endblock %}

templates/asesoria/ver_asesorias.html
{% include 'root.html' %}
{% load static %}
{% load widget_tweaks %}

{% load auth_extras %}


{% block content %}
<link rel="stylesheet" href="{% static '/css/responsive.css' %}">

<style>
</style>

<main class="container">
  <!-- DEBE regresar a el menu principal. -->
  <div class="row">
    <div class="col">
      <h1 id="title" class="my-3"><a href="{% url 'accounts:principal' %}"><i
            class="icon fas fa-arrow-circle-left pr-4"></i></a>Mis asesorías</h1>
    </div>
  </div>

  <div class="row my-3">
    <div class="col">
      <!-- Datos de la ventan en caso de ser asesorado -->
      {% if request.user|has_group:"asesorados" %}
      <p class="text-secondary">Aquí se muestra la lista de tus asesorías registradas en el sistema, es posible cancelar
        aquellas en estado "pendiente" o escribir un comentario en las finalizadas.<b> Este historial será borrado al
          término de cada semestre</b>, puedes generar un respaldo en la opción de reportes.</p>
      <!-- En caso de ser asesor -->
      {% else %}
      <p class="text-secondary">Aquí se muestra la lista de sus asesorías registradas en el sistema, podra aceptar o
        rechazar las solicitudes de alumnos, cancelar aquellas en estado "pendiente" y finalizar con un comentario las
        ya aceptadas.<b> Este historial será borrado al término de cada semestre</b>, puede generar un respaldo en la
        opción de reportes.</p>
      {% endif %}
    </div>
  </div>

  <!-- Opcion de filtrado-->
  <form class="form-inline justify-content-end" method="get">
    <div class="form-group">
      {% render_field filtro.form.estado class="custom-select" %}
    </div>
    <button class="btn my-btn col-auto mb-auto ml-2" type="submit">Filtrar</button>
  </form>



  <!-- Tarjeta de asesoria -->
  {% for asesoria in asesorias %}
  <div class="card my-3 my-card">
    <!-- Revisar el estado -->
    <div class="card-header {{asesoria.estado}} text-right">
      <h5 class="{{asesoria.estado}} mr-3" title="Estado">{{asesoria.get_estado_display}}</h5>
    </div>
    <!-- Datos -->
    <div class="row no-gutters">
      <!-- Nombre y foto del asesor / asesorado...  -->
      <div class="col-md-8">
        <div class="card-body">
          <h6 class="card-text text-secondary">Asesoría con</h6>
          <h3 class="card-title">
            <img class="mr-2" src="{% static 'images/user.svg' %}" height="40" alt="Foto de perfil">
            {% if request.user|has_group:"asesorados" %}
            {% if asesoria.asesor.nombre %}
            {{asesoria.asesor.nombre}}
            {% else %}
            {{asesoria.asesor}}
            {% endif %}
            {% else %}
            {{asesoria.asesorado.nombre}}
            {% endif %}
          </h3>
          <!-- Tema, Fecha, Hora, Lugar...  -->
          <h5 class="card-text my-3"><strong>{{asesoria.subtema.nombre}}</strong></h5>
          <ul class="list-unstyled my-1">
            <li class="card-text"><strong>{{ asesoria.fecha_asesoria|date:"l d M Y" }}</strong> a las
              <strong> {{ asesoria.fecha_asesoria|time:"H:i" }}</strong> hrs.
            </li>
            <li class="card-text font-weight-light">Lugar:
              {% if asesoria.asesor.lugar_asesoria %}
              {{asesoria.asesor.lugar_asesoria}}
              {% else %}
              Acordar con el asesor.
              {% endif %}
            </li>
          </ul>
        </div>
      </div>
      <!-- Boton/botones de accion -->
      <div class="col-auto m-auto">
        <div class="card-body">
          {% if request.user|has_group:"asesorados" %}
          {% if asesoria.estado == 'pendiente' or asesoria.estado == 'aceptada' %}
          <a role="button" href="{% url 'asesoria:cancelar_asesoria' asesoria.id %}"
            class="btn-lg btn-secondary">Cancelar</a>
          {% endif %}
          {% else %}
          {% if asesoria.estado == 'pendiente' %}
          <a role="button" href="{% url 'asesoria:aceptar_asesoria' asesoria.id %}"
            class="btn-lg btn-success mr-4">Aceptar</a>
          <a role="button" href="{% url 'asesoria:rechazar_asesoria' asesoria.id %}"
            class="btn-lg btn-secondary">Rechazar</a>
          {% elif asesoria.estado == 'aceptada' %}
          <a role="button" href="{% url 'asesoria:finalizar_asesoria' asesoria.id %}"
            class="btn-lg btn-success mr-4">Finalizar</a>
          <a role="button" href="{% url 'asesoria:cancelar_asesoria' asesoria.id %}"
            class="btn-lg btn-secondary">Cancelar</a>
          {% endif %}
          {% endif %}
        </div>
      </div>
    </div>

    <!-- Para ver detalles -->
    <div class="card-footer text-right">
      <a class="card-link" href="{% url 'asesoria:detalle_asesoria' asesoria.id %}">
        Ver detalles
      </a>
    </div>
  </div>

  {% endfor%}

</main>

{% endblock %}