app/urls.py
from django.contrib import admin
from django.urls import path, include
import os

urlpatterns = [
    path('', include(('accounts.urls', 'accounts'))),
    path('asesoria/', include(('asesoria.urls', 'asesoria'))),
    path('admin/', admin.site.urls),
]

apps/accounts/urls.py
from django.urls import path, reverse_lazy
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_vies
from .views import ListarMaterias
from . import views


app_name = 'accounts'
urlpatterns = [
    path('', views.principal, name='principal'),
    path('registro/', views.registro, name='registro'),
    path('ingreso/', views.ingreso, name='ingreso'),
    path('salir/', views.salir, name='salir'),
    path('configurar/', views.configurar, name='configurar'),
    path('configurar/contrasena/', views.contrasena, name='contrasena'),
    path('configurar/horario/', views.horario, name='horario'),
    path('configurar/horario/eliminar/<str:pk>/', views.eliminarHorario, name='eliminar_horario'),
    path('contrasena_restablecer/',
         auth_vies.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done'),
                                             extra_context={'hide_logout': True, 'hide_config': True}),
         name='reset_password'),
    path('contrasena_restablecer_enviar/', auth_vies.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('contrasena_restablecer/<uidb64>/<token>/', auth_vies.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('contrasena_restablecer_terminado/',
         auth_vies.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('materia/', ListarMaterias.as_view(), name='listar_materias'),
    path('temario/', views.temario, name='temario'),
    path('temario/materia/<str:pk>', views.temarioMateriaEditar, name='temario_materia_editar'),
    path('temario/agregar/', views.temarioAgregarModal, name='temario_agregar_modal'),
    path('temario/agregar/<str:pk>/', views.temarioAgregar, name='temario_agregar'),
    path('temario/eliminar/<str:pk>/', views.temarioEliminar, name='temario_eliminar'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/messages.html
{% load static %}

{% block content %}


{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger alert-dismissible fade show">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger alert-dismissible fade show">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endif %}

{% if messages %}
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {% if 'safe' in message.tags %}
    {{ message|safe }}
    {% else %}
    {{ message }}
    {% endif %}
</div>
{% endfor %}
{% endif %}
{% endblock %}

templates/nav.html
{% load static %}
<link rel="stylesheet" href="{% static '/css/responsive.css' %}">
{% load auth_extras %}
{% block content %}

<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'accounts:principal' %}">
            <img src="{% static 'images/Logo.png' %}" width="75" height="40" alt="Wass logo" title="Menu Principal">
        </a>
        
        <ul class="navbar-nav d-flex flex-row">
            <li class="nav-item">
                {% if not hide_config %}
                <li class="nombre navbar-text mr-3" title="Usuario">{{user.username}}</li>
                <a title="Configurar perfil" href="{% url 'accounts:configurar' %}">
                    <i class="icon fas fa-user-circle mr-3"></i>
                </a>
                {% endif %}
                {% if not hide_logout %}
                <a title="Cerrar sesión" href="{% url 'accounts:salir'%}">
                    <i class="icon fas fa-sign-out-alt"></i>
                </a>
                {% endif %}
            </li>
        </ul>
        
    </div>
</nav>

<div class="container">
    {% if title %}
    <div class="row align-items-center">
        <a href="{{request.META.HTTP_REFERER}}">
            <i class="icon fas fa-arrow-circle-left px-4"></i>
        </a>
        <h1 id="title" class="my-3">
            {{title}}
        </h1>
    </div>
    {% endif %}
</div>


{% endblock %}

templates/root.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap stylesheet-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- Icons template <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>-->
    <!-- Our css stylesheet-->
    <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" href="{% static '/css/responsive.css' %}">
    <!-- Our js script-->
    <link rel="text/javascript" href="{% static '/js/script.js' %}">
    <!--- Fonts Icon  -->
    <link rel="shortcut icon" type="image/png" href="{% static 'images/icon.png' %}"/>
    <script src="https://kit.fontawesome.com/cf8f2989e3.js" crossorigin="anonymous"></script>
    <title>
    WASS
    {% if title %} | {{title}}{% endif %}
    </title>
</head>

<body>
    {% if not hide_navbar %}
        {% include 'nav.html' %}
    {% endif %}

    {% include 'messages.html' %}

    {% block content %}


    {% endblock %}

</body>
    <!---Bootstrap v4.5 JS link-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

    {% block extrajs %}
    
    {% endblock extrajs %}

</html>